# Generated by Django 2.0.7 on 2019-04-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_questions_is_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreeQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='点赞IP地址')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Questions', verbose_name='面试题')),
            ],
            options={
                'db_table': 'agree_questions',
            },
        ),
    ]
