# Generated by Django 2.0.7 on 2019-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ip', models.CharField(max_length=30, verbose_name='登陆IP地址')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('ERROR', '失败')], default='SUCCESS', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'q_user_login',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_ip', models.CharField(max_length=30, verbose_name='访问用户的IP地址')),
                ('q_id', models.IntegerField(null=True, verbose_name='用户访问的面试题id值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'q_visit',
            },
        ),
    ]
