# Generated by Django 2.0.7 on 2019-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='from_company',
            field=models.CharField(max_length=100, null=True, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_show',
            field=models.IntegerField(default=1, verbose_name='是否公布'),
        ),
        migrations.AddField(
            model_name='questions',
            name='pri_key',
            field=models.CharField(max_length=100, null=True, verbose_name='关键字'),
        ),
    ]
