# Generated by Django 2.0.7 on 2019-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190417_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_delete',
            field=models.IntegerField(default=0, verbose_name='是否删除'),
        ),
    ]
