# Generated by Django 2.0.7 on 2019-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_questions_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_like',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
