# Generated by Django 2.0.7 on 2019-04-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=4, verbose_name='用户名称')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否被删除')),
            ],
            options={
                'db_table': 'q_user',
            },
        ),
    ]
